misc:
  threads: 100  # Number of threads to use for sending messages
  lang: "en"  # Language to use for Omegle (en, de, es, fr, and so on...) -> "Alpha 2"-> https://www.nationsonline.org/oneworld/country_code_list.htm 
  channel_type: "text"  # Text/Cam
  show_typing: true # Shows the "Typing..." message to the user on the other end before sending the message
proxy:
  use_own: false # "true" if using own proxies, "false" if scraping proxies
  type: "http"  # http/socks4/socks4a/socks5
  timeout: 10 # Proxy timeout in seconds
message:
  content: "Hello, how are you?"  # The message to send
  delay: 2  # Delay in seconds between each message
  use_emoji: true # Adds a random emoji to the end of each message
  use_prefix: false  # Adds a random string to the end of each message
  use_suffix: false  # Adds a random string to the start of each message
  delay_after: 2 # How long until disconnect after the message has been sent
  topics: [] # Topics to queue inside of ; example ["youtube", "tiktok"].